### ISSUE TITLE
Thank you and questions

### ISSUE THREAD

**Issue by syang19** [philbot9/youtube-comment-scraper-cli#1]
Dear Phil,

Thank you so much for sharing this program. I found it very easy to implement and helpful. I am working on a research project that requires content analysis about those comments from YouTube videos. 

When I retrieve comments, I found some of them written in several languages other than English. Do you know any easy ways to auto-translate them to English?

Looking forward to your reply.

Many thanks,
Shuo

**Comment by philbot9** [comment]
Thank you, I'm glad to hear it's useful. Maybe have a look at Google's Translate API (https://cloud.google.com/translate/), other than that I don't know.

Closing as this goes beyond the scope of this project.
