### ISSUE TITLE
Video ids that start with a hyphen are not recognized

### ISSUE THREAD

**Issue by 174n** [philbot9/youtube-comment-scraper-cli#19]
Here is an example

```
youtube-comment-scraper -gvKdihhOJc
```

**Comment by philbot9** [comment]
Hi Rundik,

The problem is that the dash causes the video ID to be interpreted as a command line option. 

On POSIX systems, you can signify the end of the command line options using a double-dash (`--`). 

The command should be:

```
youtube-comment-scraper -- -gvKdihhOJc
```
