### ISSUE TITLE
Does not work in Windows 10

### ISSUE THREAD

**Issue by ProximaNova** [philbot9/youtube-comment-scraper-cli#21]
I installed with npm but got this error:

E:\cs>youtube-comment-scraper
'youtube-comment-scraper' is not recognized as an internal or external command,
operable program or batch file.

Also did not work:
E:\cs>C:\Users\user\AppData\Roaming\npm\node_modules\youtube-comment-scraper-cli\bin\youtube-comment-scraper --help
'C:\Users\user\AppData\Roaming\npm\node_modules\youtube-comment-scraper-cli\bin\youtube-comment-scraper' is not recognized as an internal or external command,
operable program or batch file.

**Comment by philbot9** [comment]
Sorry, not a Windows user. The program is confirmed to be working on Windows 10 with Windows PowerShell.

Please refer to the npm manual (https://docs.npmjs.com/downloading-and-installing-packages-globally) or post your question on an npm support forum.

**Comment by realtechspecs** [comment]
I keep getting CommandNotFoundException. 'youtube-comment-scraper' is not recognized as an internal or external command, operable program or batch file.

any clues? OS is windows 10
