### ISSUE TITLE
Handle VideoIDs that start with a "-"

### ISSUE THREAD

**Issue by bigokro** [philbot9/youtube-comment-scraper-cli#23]
In trying to scrape the following video, I discovered that it's treating the VideoID like another command-line option (one that doesn't exist):

https://youtu.be/-GNO_zEeiYU

> `youtube-comment-scraper -f csv -o hannity.csv "-GNO_zEeiYU"`
> error: unknown option `-G'

I'm trying to send a patch to fix it, but there's so much magic going on there that it looks like yargs isn't even explicitly called XD
I'll keep trying, but I'm more of a back-end dev, so this is all a bit of a mystery to me...

**Comment by philbot9** [comment]
Please refer to https://github.com/philbot9/youtube-comment-scraper-cli/issues/19#issuecomment-531235625

**Comment by bigokro** [comment]
D'oh! Thanks!
Just out of curiosity, how exactly DOES the cli parsing work? I can't find the setup anywhere in any of your projects.

**Comment by philbot9** [comment]
CLI args are parsed in the bin file using the [commander](https://www.npmjs.com/package/commander) npm package.

https://github.com/philbot9/youtube-comment-scraper-cli/blob/master/bin/youtube-comment-scraper
