### ISSUE TITLE
fails on some VideoIDs

### ISSUE THREAD

**Issue by phrackerjack** [philbot9/youtube-comment-scraper-cli#24]
Doesn't allow for VideoIDs whose 1st character is a dash, as it thinks you're passing it an option; quotes around the VideoID don't help. My experience using a valid ID:

**youtube-comment-scraper -s -f json -d "-2E18bwbbHk"**
**error: unknown option `-2'**

**Comment by philbot9** [comment]
https://github.com/philbot9/youtube-comment-scraper-cli/issues/19#issuecomment-531235625
